In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install keras
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install keras_preprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.7 MB/s eta 0:00:00


##**Importing Libraries**


In [ ]:
!pip install keras_preprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from keras.layers.core import Dense, SpatialDropout1D
from keras.layers.convolutional import Conv1D
from tensorflow.keras.layers import Embedding
from keras.layers.pooling import GlobalMaxPooling1D
from keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
import collections
import nltk
import numpy as np
import codecs
import string as st
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def remove_stopwords(text):
    stopword=nltk.corpus.stopwords.words('english')
    stopword.remove('not')
    w=[word for word in nltk.word_tokenize(text) if word not in stopword]
    return ' '.join(w)

In [ ]:
def remove_punctuation(text):
    w=[word for word in text if word not in st.punctuation]
    return ' '.join(w)

In [ ]:
INPUT_FILE = "/content/train_2k.txt"


##**Dataset Preparation and Cleaning**

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
counter = collections.Counter()
maxlen = 0
xs, ys = [], []



fin = codecs.open(INPUT_FILE, "r", encoding='utf-8')
for line in fin:
  
    label, sent = line.strip().split("\t") #Stripping the dataset based on tab. That is stripping label from sentence
    print("Label: ", label)
    print("Sentence: ",sent)
    
    words = nltk.word_tokenize(sent)
    print("Afert Tokenizing: ",words)

    wordsExcludingPunctuationMarks=remove_punctuation(words)
    print("Truncating punctuation:", wordsExcludingPunctuationMarks)

    wordsExcludingStopWords=remove_stopwords(wordsExcludingPunctuationMarks)
    print("Truncating StopWords:", wordsExcludingStopWords)

    if len(wordsExcludingStopWords) > maxlen: #For calculating the maximum number of words in a sentence
        maxlen = len(wordsExcludingStopWords) 
    for wordExcludingStopWords in wordsExcludingStopWords:
        counter[wordExcludingStopWords] += 1 #Putting the frequency of each  word in a dictionary
    print("***************************************************************************************")

    ys.append(int(label))
    xs.append(''.join(wordsExcludingStopWords))


fin.close()
    


Streaming output truncated to the last 5000 lines.
Truncating StopWords: follow sundayy truecyrusfans ADD HER ADD HERR
***************************************************************************************
Label:  0
Sentence:  @LexAve twitpic is not working for me  what is it?? lol
Afert Tokenizing:  ['@', 'LexAve', 'twitpic', 'is', 'not', 'working', 'for', 'me', 'what', 'is', 'it', '?', '?', 'lol']
Truncating punctuation: LexAve twitpic is not working for me what is it lol
Truncating StopWords: LexAve twitpic not working lol
***************************************************************************************
Label:  1
Sentence:  @sleemol I love doing that; let's do it some time that isn't today
Afert Tokenizing:  ['@', 'sleemol', 'I', 'love', 'doing', 'that', ';', 'let', "'s", 'do', 'it', 'some', 'time', 'that', 'is', "n't", 'today']
Truncating punctuation: sleemol I love doing that let 's do it some time that is n't today
Truncating StopWords: sleemol I love let 's time n't today

In [ ]:
xs

["Starting back work today Looks like 'll raining next couple days",
 'Sugar levels dropping ... munchies setting Luckily I black chocolate Toblerone fridge',
 'karineb22 yeah great summer break',
 'hannah montana good going read twilight',
 'Mayra326 aww fun I 3D last week',
 'Worried cat Took vet blood work etc normal hes still not eatting',
 'Dancing cloud nine significant .... got accepted Nursing School Del Mar College fall',
 'asherroth omg pls take one bacardi dr pepper',
 "How get stuck watchin everything Smh Damn n im hungry n't ne breakfast",
 'sunday67 5 days remaining',
 'DavidBedwell I really really Oh dear',
 "im exhausted LOOONG day .... feels good PJ 's bed resting .... still got ta study quiz tomorrow",
 "meghanelaine I knew I agreeing -- I 'm sorry n't clear",
 'soooooo sick right',
 'lamere thank much looking pics makes want one',
 'rahulrakesh hahah ... treated Ex boss',
 'It means wish werent going',
 '_CINNA_ ben chillin day',
 "maryfrance get JK I 'm going miss",

##**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(xs, ys, test_size=0.20, random_state=0)
Xtrain

['/pointcast making feel old',
 "cooking Nigella 's Gammon jersey royals salad",
 "MIKEYFUENTES important people asking today occurred I n't really know story",
 'Crodita Preparandome para ir al work',
 'surfichris The next season final season',
 "kayleighford figuring different time zones n't strongest point",
 "JustcallmeMac No worries I 've never one heaps sleep",
 'failed Customer Focus ironic director last job told felt inferior due cards/letters/flowers clients',
 'lynn1144 sorry 2 hear',
 'pleased line drawing orchid wish painting good',
 'ohsoretro 93 right',
 'Staying working websites alas work never ends Will head river tomorrow though',
 'Baking cake kiddies They keep asking talk Ricky Joey I wish could Ricky Joey movie night',
 'gorjuss Happy Anniversary Mr G',
 'ShirleyMcLaugh I ask aventure could work back said',
 "Ayvii Can tell SmoovezWorld im sorry laughing hard getting fire micky D 's love .. lol",
 "legendarcy 's annoying n't Right I 'd love something heroy BUT lot x

In [ ]:
#tf idf
tf_idf = TfidfVectorizer()
#applying tf idf to training data
Xtrain_tf = tf_idf.fit_transform(Xtrain)
#applying tf idf to training data
Xtrain_tf = tf_idf.transform(Xtrain)
print("n_samples: %d, n_features: %d" % Xtrain_tf.shape)

n_samples: 1600, n_features: 5095


In [ ]:
#transforming test data into tf-idf matrix
Xtest_tf = tf_idf.transform(Xtest)
print("n_samples: %d, n_features: %d" % Xtest_tf.shape)

n_samples: 400, n_features: 5095


##**Naive Bayes**

In [ ]:
#naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(Xtrain_tf, Ytrain)
#predicted y
y_pred = naive_bayes_classifier.predict(Xtest_tf)

In [ ]:

from sklearn import metrics
print(metrics.classification_report(Ytest, y_pred, target_names=['Positive', 'Negative']))


              precision    recall  f1-score   support

    Positive       0.60      0.77      0.67       186
    Negative       0.74      0.55      0.63       214

    accuracy                           0.65       400
   macro avg       0.67      0.66      0.65       400
weighted avg       0.67      0.65      0.65       400



In [ ]:
print(metrics.confusion_matrix(Ytest, y_pred))

[[144  42]
 [ 97 117]]


##**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
LRClassification=LogisticRegression()
LRClassification.fit(Xtrain_tf, Ytrain)
y_pred=LRClassification.predict(Xtest_tf)


In [ ]:

from sklearn import metrics
print(metrics.classification_report(Ytest, y_pred, target_names=['Positive', 'Negative']))


              precision    recall  f1-score   support

    Positive       0.60      0.74      0.66       186
    Negative       0.72      0.58      0.64       214

    accuracy                           0.65       400
   macro avg       0.66      0.66      0.65       400
weighted avg       0.66      0.65      0.65       400



In [ ]:
print(metrics.confusion_matrix(Ytest, y_pred))

[[137  49]
 [ 90 124]]


In [ ]:
fprLogistic, tprLogistic, thresholdsLogistic = metrics.roc_curve(Ytest,y_pred)

##**Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DTClassification=DecisionTreeClassifier(random_state=0)
DTClassification.fit(Xtrain_tf, Ytrain)
y_pred=DTClassification.predict(Xtest_tf)

In [ ]:
from sklearn import metrics
print(metrics.classification_report(Ytest, y_pred, target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.57      0.55      0.56       186
    Negative       0.62      0.64      0.63       214

    accuracy                           0.60       400
   macro avg       0.60      0.59      0.59       400
weighted avg       0.60      0.60      0.60       400



In [ ]:
print(metrics.confusion_matrix(Ytest, y_pred))

[[103  83]
 [ 78 136]]


In [ ]:
fprDecision, tprDecision, thresholdsDecision = metrics.roc_curve(Ytest,y_pred)

##**SVM**

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(Xtrain_tf, Ytrain)

#Predict the response for test dataset
y_pred = clf.predict(Xtest_tf)

In [ ]:
from sklearn import metrics
print(metrics.classification_report(Ytest, y_pred, target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.63      0.75      0.68       186
    Negative       0.74      0.61      0.67       214

    accuracy                           0.68       400
   macro avg       0.68      0.68      0.68       400
weighted avg       0.69      0.68      0.68       400



In [ ]:
print(metrics.confusion_matrix(Ytest, y_pred))

[[140  46]
 [ 83 131]]


In [ ]:
fprSVM, tprSVM, thresholdsSVM = metrics.roc_curve(Ytest,y_pred)

##**ROC**

In [ ]:
# from matplotlib import pyplot as plt
# from sklearn.metrics import plot_roc_curve
# from sklearn.metrics import auc

# plt.figure(1)
# plt.figure(figsize=(8, 6), dpi=300)
# plt.plot([0, 1], [0, 1], 'k--')


# auc_Logistic = auc(fprLogistic, tprLogistic)
# auc_Decision = auc(fprDecision , tprDecision)
# auc_SVM = auc(fprSVM, tprSVM)

# plt.plot(fprLogistic, tprLogistic, label='Logistic Regression (area = {:.3f})'.format(auc_Logistic))
# plt.plot(fprDecision, tprDecision, label='Decision Tree (area = {:.3f})'.format(auc_Decision))
# plt.plot(fprSVM, tprSVM, label='SVM (area = {:.3f})'.format(auc_SVM))
# plt.legend(loc='lower right')
# plt.show()

ImportError: ignored